# Classification Techniques :
    1. KNN
    2. Support Vector
    3. Naive Bayes
    4. Decision Tree
    5. Logistic Regression
    6. Random Forest

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
data=load_iris(as_frame=True)
X=data.data
Y=data.target

# 1.KNN

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.20)

In [5]:
from sklearn.neighbors import KNeighborsClassifier

classifier=KNeighborsClassifier(n_neighbors=1)

classifier.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [6]:
y_pred=classifier.predict(x_test)
print(y_test)
print(y_pred)

15     0
60     1
80     1
148    2
56     1
79     1
88     1
145    2
26     0
129    2
53     1
68     1
106    2
81     1
82     1
41     0
98     1
33     0
44     0
43     0
70     1
140    2
118    2
10     0
40     0
23     0
7      0
97     1
114    2
52     1
Name: target, dtype: int32
[0 1 1 2 1 1 1 2 0 2 1 1 1 1 1 0 1 0 0 0 2 2 2 0 0 0 0 1 2 1]


In [7]:
from sklearn.metrics import confusion_matrix, accuracy_score

cm=confusion_matrix(y_test,y_pred)
display(cm)

print("Accuracy of the model is ",accuracy_score(y_test,y_pred)*100,"%")
print("Error rate of model is",100-accuracy_score(y_test,y_pred)*100,"%")

array([[10,  0,  0],
       [ 0, 12,  1],
       [ 0,  1,  6]], dtype=int64)

Accuracy of the model is  93.33333333333333 %
Error rate of model is 6.666666666666671 %


# Evaluate alternative K-values for better predictions

In [8]:
k_list=list(range(1,50,2))
acc_score=[]
err_rate=[]
for x in k_list:
    classifier=KNeighborsClassifier(n_neighbors=x)
    classifier.fit(x_train,y_train)
    y_pred=classifier.predict(x_test)
    print('Accuracy Score k=%d : %1.2f'%(x,accuracy_score(y_test,y_pred)))
    acc_score.append(accuracy_score(y_test,y_pred))
    err_rate.append(1-accuracy_score(y_test,y_pred))

Accuracy Score k=1 : 0.93
Accuracy Score k=3 : 0.93
Accuracy Score k=5 : 0.93
Accuracy Score k=7 : 0.93
Accuracy Score k=9 : 0.93
Accuracy Score k=11 : 0.93
Accuracy Score k=13 : 0.93
Accuracy Score k=15 : 0.93
Accuracy Score k=17 : 0.93
Accuracy Score k=19 : 0.93
Accuracy Score k=21 : 0.97
Accuracy Score k=23 : 0.93
Accuracy Score k=25 : 0.93
Accuracy Score k=27 : 0.97
Accuracy Score k=29 : 0.93
Accuracy Score k=31 : 0.97
Accuracy Score k=33 : 0.97
Accuracy Score k=35 : 0.93
Accuracy Score k=37 : 0.93
Accuracy Score k=39 : 0.93
Accuracy Score k=41 : 0.93
Accuracy Score k=43 : 0.93
Accuracy Score k=45 : 0.93
Accuracy Score k=47 : 0.93
Accuracy Score k=49 : 0.93


In [9]:
classifier=KNeighborsClassifier(n_neighbors=13)
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
display(confusion_matrix(y_test,y_pred))
display(accuracy_score(y_test,y_pred))

array([[10,  0,  0],
       [ 0, 12,  1],
       [ 0,  1,  6]], dtype=int64)

0.9333333333333333

In [10]:
print("Accuracy of the model is ",accuracy_score(y_test,y_pred)*100,"%")
print("Error rate of the model is ",round(100-accuracy_score(y_test,y_pred)*100,2),"%")

Accuracy of the model is  93.33333333333333 %
Error rate of the model is  6.67 %


In [11]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.92      0.92      0.92        13
           2       0.86      0.86      0.86         7

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30



In [12]:
#setosa
TP=cm[0,0]
TN=cm[1,1]+cm[1,2]+cm[2,1]+cm[2,2]
FN=cm[0,1]+cm[0,2]
FP=cm[1,0]+cm[2,0]
set_TPR=TP/float(TP+FN)
set_TNR=TN/float(TN+FP)
set_Pre=TP/float(TP+FP)
set_FPR=FP/float(FP+TN)
print(set_TPR)
print(set_TNR)
print(set_Pre)
print(set_FPR)
#versicolore
TP=cm[1,1]
TN=cm[0,1]+cm[0,2]+cm[2,0]+cm[2,2]
FN=cm[1,0]+cm[1,2]
FP=cm[0,1]+cm[2,1]
ver_TPR=TP/float(TP+FN)
ver_TNR=TN/float(TN+FP)
ver_Pre=TP/float(TP+FP)
ver_FPR=FP/float(FP+TN)
print(ver_TPR)
print(ver_TNR)
print(ver_Pre)
print(ver_FPR)
#virginia
TP=cm[2,2]
TN=cm[0,0]+cm[0,1]+cm[1,0]+cm[1,1]
FN=cm[2,0]+cm[2,1]
FP=cm[0,2]+cm[1,2]
vir_TPR=TP/float(TP+FN)
vir_TNR=TN/float(TN+FP)
vir_Pre=TP/float(TP+FP)
vir_FPR=FP/float(FP+TN)
print(vir_TPR)
print(vir_TNR)
print(vir_Pre)
print(vir_FPR)

1.0
1.0
1.0
0.0
0.9230769230769231
0.8571428571428571
0.9230769230769231
0.14285714285714285
0.8571428571428571
0.9565217391304348
0.8571428571428571
0.043478260869565216


In [13]:
df=pd.DataFrame({"TPR":['1','1','1'],"TNR":['0','1','0.9'],"Pre":['0.9230','0.1','0.9'],"FPR":['1','1','0']})
df.index=['Setosa','Versicolor','Virginica']
df

TPR  TNR     Pre FPR
Setosa       1    0  0.9230   1
Versicolor   1    1     0.1   1
Virginica    1  0.9     0.9   0

# 2. Support Vector

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(X,Y,test_size=0.30)

In [15]:
from sklearn.svm import SVC
model=SVC()
model.fit(x_train,y_train)

SVC()

In [16]:
pred=model.predict(x_test)

In [17]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test,pred)
display(cm)
print("Accuracy of model is:",accuracy_score(y_test,pred))
print("Error rate of model is:",1-accuracy_score(y_test,pred))

array([[11,  0,  0],
       [ 0, 12,  2],
       [ 0,  1, 19]], dtype=int64)

Accuracy of model is: 0.9333333333333333
Error rate of model is: 0.06666666666666665


In [18]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       0.92      0.86      0.89        14
           2       0.90      0.95      0.93        20

    accuracy                           0.93        45
   macro avg       0.94      0.94      0.94        45
weighted avg       0.93      0.93      0.93        45



In [19]:
#setosa
TP=cm[0,0]
TN=cm[1,1]+cm[1,2]+cm[2,1]+cm[2,2]
FN=cm[0,1]+cm[0,2]
FP=cm[1,0]+cm[2,0]
set_TPR=TP/float(TP+FN)
set_TNR=TN/float(TN+FP)
set_Pre=TP/float(TP+FP)
set_FPR=FP/float(FP+TN)
print(set_TPR)
print(set_TNR)
print(set_Pre)
print(set_FPR)
#versicolore
TP=cm[1,1]
TN=cm[0,1]+cm[0,2]+cm[2,0]+cm[2,2]
FN=cm[1,0]+cm[1,2]
FP=cm[0,1]+cm[2,1]
ver_TPR=TP/float(TP+FN)
ver_TNR=TN/float(TN+FP)
ver_Pre=TP/float(TP+FP)
ver_FPR=FP/float(FP+TN)
print(ver_TPR)
print(ver_TNR)
print(ver_Pre)
print(ver_FPR)
#virginia
TP=cm[2,2]
TN=cm[0,0]+cm[0,1]+cm[1,0]+cm[1,1]
FN=cm[2,0]+cm[2,1]
FP=cm[0,2]+cm[1,2]
vir_TPR=TP/float(TP+FN)
vir_TNR=TN/float(TN+FP)
vir_Pre=TP/float(TP+FP)
vir_FPR=FP/float(FP+TN)
print(vir_TPR)
print(vir_TNR)
print(vir_Pre)
print(vir_FPR)

1.0
1.0
1.0
0.0
0.8571428571428571
0.95
0.9230769230769231
0.05
0.95
0.92
0.9047619047619048
0.08


In [20]:
df=pd.DataFrame({"TPR":['1','1','1'],"TNR":['0','0.9375','1'],"Pre":['1','0','1'],"FPR":['0.96875','0.928571','0.03125']})
df.index=['Setosa','Versicolor','Virginica']
df

TPR     TNR Pre       FPR
Setosa       1       0   1   0.96875
Versicolor   1  0.9375   0  0.928571
Virginica    1       1   1   0.03125

# 3. Naivy Bayes

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test =train_test_split(X,Y,test_size=0.2)

In [22]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [23]:
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(X_train,y_train)

GaussianNB()

In [24]:
y_pred=classifier.predict(X_test)
y_pred

array([1, 2, 2, 0, 0, 0, 0, 2, 0, 1, 0, 0, 2, 0, 0, 2, 0, 2, 0, 1, 0, 0,
       1, 1, 1, 2, 0, 2, 0, 0])

In [25]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(y_test,y_pred)
display(cm)
print("Accuracy of model is:",accuracy_score(y_test,y_pred))
print("Error rate of model is:",1-accuracy_score(y_test,y_pred))

array([[16,  0,  0],
       [ 0,  5,  1],
       [ 0,  1,  7]], dtype=int64)

Accuracy of model is: 0.9333333333333333
Error rate of model is: 0.06666666666666665


In [26]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.83      0.83      0.83         6
           2       0.88      0.88      0.88         8

    accuracy                           0.93        30
   macro avg       0.90      0.90      0.90        30
weighted avg       0.93      0.93      0.93        30



In [27]:
#setosa
TP=cm[0,0]
TN=cm[1,1]+cm[1,2]+cm[2,1]+cm[2,2]
FN=cm[0,1]+cm[0,2]
FP=cm[1,0]+cm[2,0]
set_TPR=TP/float(TP+FN)
set_TNR=TN/float(TN+FP)
set_Pre=TP/float(TP+FP)
set_FPR=FP/float(FP+TN)
print(set_TPR)
print(set_TNR)
print(set_Pre)
print(set_FPR)
#versicolore
TP=cm[1,1]
TN=cm[0,1]+cm[0,2]+cm[2,0]+cm[2,2]
FN=cm[1,0]+cm[1,2]
FP=cm[0,1]+cm[2,1]
ver_TPR=TP/float(TP+FN)
ver_TNR=TN/float(TN+FP)
ver_Pre=TP/float(TP+FP)
ver_FPR=FP/float(FP+TN)
print(ver_TPR)
print(ver_TNR)
print(ver_Pre)
print(ver_FPR)
#virginia
TP=cm[2,2]
TN=cm[0,0]+cm[0,1]+cm[1,0]+cm[1,1]
FN=cm[2,0]+cm[2,1]
FP=cm[0,2]+cm[1,2]
vir_TPR=TP/float(TP+FN)
vir_TNR=TN/float(TN+FP)
vir_Pre=TP/float(TP+FP)
vir_FPR=FP/float(FP+TN)
print(vir_TPR)
print(vir_TNR)
print(vir_Pre)
print(vir_FPR)

1.0
1.0
1.0
0.0
0.8333333333333334
0.875
0.8333333333333334
0.125
0.875
0.9545454545454546
0.875
0.045454545454545456


In [28]:
df=pd.DataFrame({"TPR":['1','1','1'],"TNR":['0','1','0.8888888'],"Pre":['0.88888','0.11111','0.88888'],"FPR":['1','1','0']})
df.index=['Setosa','Versicolor','Virginica']
df

TPR        TNR      Pre FPR
Setosa       1          0  0.88888   1
Versicolor   1          1  0.11111   1
Virginica    1  0.8888888  0.88888   0

# 4. Decision Tree

In [29]:
from sklearn.model_selection  import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,random_state=50,test_size=0.50)

In [30]:
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier()
classifier.fit(x_train,y_train)

DecisionTreeClassifier()

In [31]:
y_pred=classifier.predict(x_test)

In [32]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [33]:
print("Train Data accuracy:",accuracy_score(y_true=y_train,y_pred=classifier.predict(x_train)))

Train Data accuracy: 1.0


In [34]:
print("Accuracy of the model is ",accuracy_score(y_test,y_pred)*100,"%")
print("Error rate of the model is ",round(100-accuracy_score(y_test,y_pred)*100,2),"%")

Accuracy of the model is  97.33333333333334 %
Error rate of the model is  2.67 %


In [35]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
print(classification_report(y_test,y_pred))
cm=confusion_matrix(y_test,y_pred)
cm

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.96      0.96      0.96        26
           2       0.96      0.96      0.96        24

    accuracy                           0.97        75
   macro avg       0.97      0.97      0.97        75
weighted avg       0.97      0.97      0.97        75



array([[25,  0,  0],
       [ 0, 25,  1],
       [ 0,  1, 23]], dtype=int64)

In [36]:
#setosa
TP=cm[0,0]
TN=cm[1,1]+cm[1,2]+cm[2,1]+cm[2,2]
FN=cm[0,1]+cm[0,2]
FP=cm[1,0]+cm[2,0]
set_TPR=TP/float(TP+FN)
set_TNR=TN/float(TN+FP)
set_Pre=TP/float(TP+FP)
set_FPR=FP/float(FP+TN)
print(set_TPR)
print(set_TNR)
print(set_Pre)
print(set_FPR)
#versicolore
TP=cm[1,1]
TN=cm[0,1]+cm[0,2]+cm[2,0]+cm[2,2]
FN=cm[1,0]+cm[1,2]
FP=cm[0,1]+cm[2,1]
ver_TPR=TP/float(TP+FN)
ver_TNR=TN/float(TN+FP)
ver_Pre=TP/float(TP+FP)
ver_FPR=FP/float(FP+TN)
print(ver_TPR)
print(ver_TNR)
print(ver_Pre)
print(ver_FPR)
#virginia
TP=cm[2,2]
TN=cm[0,0]+cm[0,1]+cm[1,0]+cm[1,1]
FN=cm[2,0]+cm[2,1]
FP=cm[0,2]+cm[1,2]
vir_TPR=TP/float(TP+FN)
vir_TNR=TN/float(TN+FP)
vir_Pre=TP/float(TP+FP)
vir_FPR=FP/float(FP+TN)
print(vir_TPR)
print(vir_TNR)
print(vir_Pre)
print(vir_FPR)

1.0
1.0
1.0
0.0
0.9615384615384616
0.9583333333333334
0.9615384615384616
0.041666666666666664
0.9583333333333334
0.9803921568627451
0.9583333333333334
0.0196078431372549


In [37]:
df=pd.DataFrame({"TPR":['1','1','1'],"TNR":['0','0.961538','0.958333'],"Pre":['0.961538','0.0416666','0.958333'],"FPR":['0.980392','0.95833','0.01960']})
df.index=['Setosa','Versicolor','Virginica']
df

TPR       TNR        Pre       FPR
Setosa       1         0   0.961538  0.980392
Versicolor   1  0.961538  0.0416666   0.95833
Virginica    1  0.958333   0.958333   0.01960

# 5. Logistic Regression

In [38]:
from sklearn.model_selection  import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,random_state=42,test_size=0.20)

In [39]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

C:\Users\FLUTE\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [40]:
pred=model.predict(x_test)
pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [41]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
print(classification_report(y_test,pred))
print("Accuracy of the model is ",accuracy_score(y_test,pred)*100,"%")
print("Error rate of the model is ",round(100-accuracy_score(y_test,pred)*100,2),"%")
cm=confusion_matrix(y_test,pred)
cm

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Accuracy of the model is  100.0 %
Error rate of the model is  0.0 %


array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [42]:
#setosa
TP=cm[0,0]
TN=cm[1,1]+cm[1,2]+cm[2,1]+cm[2,2]
FN=cm[0,1]+cm[0,2]
FP=cm[1,0]+cm[2,0]
set_TPR=TP/float(TP+FN)
set_TNR=TN/float(TN+FP)
set_Pre=TP/float(TP+FP)
set_FPR=FP/float(FP+TN)
print(set_TPR)
print(set_TNR)
print(set_Pre)
print(set_FPR)
#versicolore
TP=cm[1,1]
TN=cm[0,1]+cm[0,2]+cm[2,0]+cm[2,2]
FN=cm[1,0]+cm[1,2]
FP=cm[0,1]+cm[2,1]
ver_TPR=TP/float(TP+FN)
ver_TNR=TN/float(TN+FP)
ver_Pre=TP/float(TP+FP)
ver_FPR=FP/float(FP+TN)
print(ver_TPR)
print(ver_TNR)
print(ver_Pre)
print(ver_FPR)
#virginia
TP=cm[2,2]
TN=cm[0,0]+cm[0,1]+cm[1,0]+cm[1,1]
FN=cm[2,0]+cm[2,1]
FP=cm[0,2]+cm[1,2]
vir_TPR=TP/float(TP+FN)
vir_TNR=TN/float(TN+FP)
vir_Pre=TP/float(TP+FP)
vir_FPR=FP/float(FP+TN)
print(vir_TPR)
print(vir_TNR)
print(vir_Pre)
print(vir_FPR)

1.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0


In [43]:
df=pd.DataFrame({"TPR":['1','1','1'],"TNR":['0','1','1'],"Pre":['1','0','1'],"FPR":['1','1','0']})
df.index=['Setosa','Versicolor','Virginica']
df

TPR TNR Pre FPR
Setosa       1   0   1   1
Versicolor   1   1   0   1
Virginica    1   1   1   0

# 6. Random Forest

In [45]:
from sklearn.model_selection  import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,random_state=42,test_size=0.20)

In [46]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=10,criterion='entropy',random_state=42,oob_score=True)
model.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, oob_score=True,
                       random_state=42)

In [47]:
pred=model.predict(x_test)
pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [48]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
print(classification_report(y_test,pred))
print("Accuracy of the model is ",accuracy_score(y_test,pred)*100,"%")
print("Error rate of the model is ",round(100-accuracy_score(y_test,pred)*100,2),"%")
cm=confusion_matrix(y_test,pred)
cm

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Accuracy of the model is  100.0 %
Error rate of the model is  0.0 %


array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]], dtype=int64)

In [49]:
#setosa
TP=cm[0,0]
TN=cm[1,1]+cm[1,2]+cm[2,1]+cm[2,2]
FN=cm[0,1]+cm[0,2]
FP=cm[1,0]+cm[2,0]
set_TPR=TP/float(TP+FN)
set_TNR=TN/float(TN+FP)
set_Pre=TP/float(TP+FP)
set_FPR=FP/float(FP+TN)
print(set_TPR)
print(set_TNR)
print(set_Pre)
print(set_FPR)
#versicolore
TP=cm[1,1]
TN=cm[0,1]+cm[0,2]+cm[2,0]+cm[2,2]
FN=cm[1,0]+cm[1,2]
FP=cm[0,1]+cm[2,1]
ver_TPR=TP/float(TP+FN)
ver_TNR=TN/float(TN+FP)
ver_Pre=TP/float(TP+FP)
ver_FPR=FP/float(FP+TN)
print(ver_TPR)
print(ver_TNR)
print(ver_Pre)
print(ver_FPR)
#virginia
TP=cm[2,2]
TN=cm[0,0]+cm[0,1]+cm[1,0]+cm[1,1]
FN=cm[2,0]+cm[2,1]
FP=cm[0,2]+cm[1,2]
vir_TPR=TP/float(TP+FN)
vir_TNR=TN/float(TN+FP)
vir_Pre=TP/float(TP+FP)
vir_FPR=FP/float(FP+TN)
print(vir_TPR)
print(vir_TNR)
print(vir_Pre)
print(vir_FPR)

1.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0
1.0
1.0
1.0
0.0
